CREATE TABLE users
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username           VARCHAR(50)  NOT NULL,
    password_hash      VARCHAR(100) NOT NULL,
    full_name          VARCHAR(150) NOT NULL,
    phone              VARCHAR(20),
    role               VARCHAR(20)  NOT NULL CHECK (role IN ('ADMIN', 'SUPERVISOR', 'EMPLOYEE', 'CUSTOMER')),
    phone_verified_at  TIMESTAMP,
    active             BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at         TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX ux_users_username ON users (lower(username));
CREATE UNIQUE INDEX ux_users_phone ON users (phone) WHERE phone IS NOT NULL;
CREATE INDEX ix_users_role ON users (role);

CREATE TABLE refresh_tokens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES users (id),
    token_hash  VARCHAR(255) NOT NULL UNIQUE,
    expires_at  TIMESTAMP    NOT NULL,
    revoked     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE INDEX ix_refresh_tokens_user_id ON refresh_tokens (user_id);
CREATE INDEX ix_refresh_tokens_expires_at ON refresh_tokens (expires_at);

CREATE TABLE login_logs
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(50) NOT NULL,
    role        VARCHAR(20) NOT NULL,
    action      VARCHAR(20) NOT NULL,
    ip_address  VARCHAR(45),
    created_at  TIMESTAMP   NOT NULL DEFAULT now()
);

CREATE INDEX ix_login_logs_username ON login_logs (username);
CREATE INDEX ix_login_logs_created_at ON login_logs (created_at DESC);

CREATE TABLE menu_items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   BIGINT REFERENCES menu_items (id),
    menu_key    VARCHAR(100) NOT NULL UNIQUE,
    icon        VARCHAR(50)  NOT NULL,
    route       VARCHAR(255),
    sort_order  INT          NOT NULL DEFAULT 0,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE INDEX ix_menu_items_parent_sort ON menu_items (parent_id, sort_order);

CREATE TABLE menu_permissions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_item_id  BIGINT      NOT NULL REFERENCES menu_items (id) ON DELETE CASCADE,
    role          VARCHAR(20) NOT NULL CHECK (role IN ('ADMIN', 'SUPERVISOR', 'EMPLOYEE', 'CUSTOMER'))
);

CREATE UNIQUE INDEX ux_menu_permissions_item_role ON menu_permissions (menu_item_id, role);
