CREATE TABLE service_categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    sort_order  INT          NOT NULL DEFAULT 0,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE INDEX ix_service_categories_sort_order ON service_categories (sort_order);

CREATE TABLE services
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id       BIGINT REFERENCES service_categories (id),
    type              VARCHAR(20)    NOT NULL CHECK (type IN ('SERVICE', 'PRODUCT')),
    name              VARCHAR(150)   NOT NULL,
    description       TEXT,
    price             NUMERIC(10, 2) NOT NULL,
    duration_minutes  INT,
    image_public_id   VARCHAR(255),
    image_url         VARCHAR(500),
    active            BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMP      NOT NULL DEFAULT now(),
    updated_at        TIMESTAMP      NOT NULL DEFAULT now()
);

CREATE INDEX ix_services_category_id ON services (category_id);
CREATE INDEX ix_services_active ON services (active);
CREATE INDEX ix_services_type ON services (type);
