CREATE TABLE promotions
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(150)   NOT NULL,
    description     TEXT,
    discount_type   VARCHAR(10)    NOT NULL CHECK (discount_type IN ('PERCENT', 'AMOUNT')),
    discount_value  NUMERIC(10, 2) NOT NULL,
    start_date      DATE           NOT NULL,
    end_date        DATE           NOT NULL,
    active          BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP      NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP      NOT NULL DEFAULT now()
);

CREATE INDEX ix_promotions_active ON promotions (active);
CREATE INDEX ix_promotions_date_range ON promotions (start_date, end_date);

CREATE TABLE promotion_services
(
    promotion_id  BIGINT NOT NULL REFERENCES promotions (id) ON DELETE CASCADE,
    service_id    BIGINT NOT NULL REFERENCES services (id) ON DELETE CASCADE,
    PRIMARY KEY (promotion_id, service_id)
);

CREATE INDEX ix_promotion_services_service_id ON promotion_services (service_id);
