CREATE TABLE bookings
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id            BIGINT REFERENCES users (id),
    walk_in_customer_name  VARCHAR(100),
    service_id             BIGINT         NOT NULL REFERENCES services (id),
    employee_id            BIGINT REFERENCES users (id),
    promotion_id           BIGINT REFERENCES promotions (id),
    channel                VARCHAR(20)    NOT NULL DEFAULT 'ONLINE' CHECK (channel IN ('ONLINE', 'WALK_IN')),
    scheduled_at           TIMESTAMP      NOT NULL,
    final_price            NUMERIC(10, 2) NOT NULL,
    discount_amount        NUMERIC(10, 2) NOT NULL DEFAULT 0,
    created_by             BIGINT REFERENCES users (id),
    status                 VARCHAR(20)    NOT NULL CHECK (status IN ('PENDING_PAYMENT', 'CONFIRMED', 'COMPLETED', 'CANCELLED')),
    notes                  VARCHAR(500),
    created_at             TIMESTAMP      NOT NULL DEFAULT now(),
    updated_at             TIMESTAMP      NOT NULL DEFAULT now()
);

CREATE INDEX ix_bookings_customer_id ON bookings (customer_id);
CREATE INDEX ix_bookings_employee_scheduled ON bookings (employee_id, scheduled_at);
CREATE INDEX ix_bookings_status ON bookings (status);
CREATE INDEX ix_bookings_scheduled_at ON bookings (scheduled_at);
CREATE INDEX ix_bookings_channel ON bookings (channel);
