CREATE TABLE shop_info
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address         TEXT,
    phone           VARCHAR(20),
    email           VARCHAR(150),
    map_url         VARCHAR(500),
    business_hours  TEXT,
    line_id         VARCHAR(100),
    facebook_url    VARCHAR(500),
    instagram_url   VARCHAR(500),
    updated_at      TIMESTAMP NOT NULL DEFAULT now()
);

INSERT INTO shop_info (id) VALUES (1);
